Convert all paths to absolute
MirServer/ubuntu-frame pull request #104
Opened 2022-10-28 20:39 UTC by graysonguarino

Fixes #93 by using `boost::filesystem::absolute()` to convert all inputted paths to absolute paths. Also deals with the error case where a user attempts to input a file as the parent directory.

2022-10-31 09:05 UTC, AlanGriffiths requested changes

2022-10-31 09:05 UTC, AlanGriffiths commented on src/background_client.cpp
> +            "Target of diagnostic path (" + path.string() + ") is a directory when it should be a file"));
I think reporting on configuration errors should include the configured value (instead or as well as the path we derive from it)

2022-10-31 09:05 UTC, AlanGriffiths commented on src/background_client.cpp
> +            "Parent of diagnostic path (" + path.parent_path().string() + ") is not a directory"));
I think reporting on configuration errors should include the configured value (instead or as well as the path we derive from it)

2022-10-31 12:45 UTC, AlanGriffiths requested changes
```
cmake-build-debug/frame --diagnostic-path nonexisting/tmp
```
Expect: an error
Actual: no error

2022-10-31 12:59 UTC, graysonguarino commented
> ```
> cmake-build-debug/frame --diagnostic-path nonexisting/tmp
> ```
> 
> Expect: an error Actual: no error

🤦 I forgot to check that case when migrating from `boost::filesystem::canonical()` to `boost::filesystem::absolute()`.

2022-10-31 13:01 UTC, AlanGriffiths commented
> I forgot to check that case

That is the problem with manual testing

2022-10-31 14:53 UTC, AlanGriffiths commented on src/background_client.cpp
> +    }
I'm not sure how many types of path are supported by boost.Filesystem, but wouldn't it be clearer to test for `is_directory` when that is the requirement?

2022-11-01 09:07 UTC, AlanGriffiths commented on src/background_client.cpp
> +
Looking through `boost::filesystem` it looks like paths can be  `is_regular_file`, `is_directory`, `is_symlink` or `is_other`. If the constraint is that it should be a file, then surely the correct test is `!is_regular_file(path)`?

2022-11-01 11:28 UTC, AlanGriffiths commented on src/background_client.cpp
> +    }
```suggestion
    if (!is_directory_file(path.parent_path()))
    {
        BOOST_THROW_EXCEPTION(std::runtime_error(
            "Parent of diagnostic path is not a directory." + formatted_path_error));
    }
```

2022-11-01 11:33 UTC, AlanGriffiths commented on src/background_client.cpp
> +    if (is_regular_file(path.parent_path()))
```suggestion
    if (!is_directory_file(path.parent_path()))
```

2022-11-03 09:31 UTC, AlanGriffiths requested changes
The code and the diagnostics should agree.

See both the latest comment and unresolved comments from before

2022-11-03 09:31 UTC, AlanGriffiths commented on src/background_client.cpp
>      }
The code and the diagnostic disagree

2022-11-03 11:18 UTC, AlanGriffiths commented on src/background_client.cpp
>      }
Doesn't reject `is_symlink` or `is_other`

2022-11-03 13:13 UTC, closed without merging