Allow configuration to assign applications to outputs
MirServer/ubuntu-frame pull request #129
Opened 2023-02-24 14:41 UTC by AlanGriffiths

Adds an `output-for-app` configuration option that allows apps to be assigned to outputs.

The output names are assigned by Mir and the app name used is the window title (as set via Wayland). In the case of wpe-webkit-mir-kiosk this is "Cog"

This can be added multiple times to the `config` option:

snap set ubuntu-frame config ="
output-for-app=OUT-1:Cog
output-for-app=OUT-2:Kodi
"

2023-02-24 14:43 UTC, AlanGriffiths commented
When testing remember that this needs to be built against ppa:mir-team/dev and that the default layout is overlapping screens. Try something like:

```plain
ubuntu-frame --x11-output 800x600:800x600 --output-for-app=OUT-2:Cog --output-for-app=OUT-1:Kodi --display-layout side_by_side
```

2023-02-24 15:46 UTC, Saviq requested changes
IMO we need this as part of the display configuration, as you could arguably have different apps mapped to different displays in different layouts.

We also need more ways to match apps, as this won't allow you to run multiple WPEs mapped to different screens.

2023-02-24 16:16 UTC, AlanGriffiths commented
> IMO we need this as part of the display configuration, as you could arguably have different apps mapped to different displays in different layouts.

That implies adding new miral APIs that allow Frame's window manager to interrogate the .display configuration. I'm not sure what that would look like, but it wouldn't be trivial.

(It seems wrong to consider wiring something as Frame specific as this into the mir libraries. Or for Frame to parse the file for itself.)

> We also need more ways to match apps, as this won't allow you to run multiple WPEs mapped to different screens.

There is existing code in Frame to use apparmor to identify other snaps, we could add that as an additional matching option?

2023-02-24 16:19 UTC, AlanGriffiths commented
> you could arguably have different apps mapped to different displays in different layouts.

We could optionally include the layout name in the mapping string?

2023-02-27 08:03 UTC, Saviq commented
> > IMO we need this as part of the display configuration, as you could arguably have different apps mapped to different displays in different layouts.
>
> That implies adding new miral APIs that allow Frame's window manager to interrogate the .display configuration. I'm not sure what that would look like, but it wouldn't be trivial.
> 
> (It seems wrong to consider wiring something as Frame specific as this into the mir libraries. Or for Frame to parse the file for itself.)

Frame could specialize the parsing, maybe registering with a key and receiving callbacks when that is encountered in the config? Or subclassing `StaticDisplayConfiguration`?

> We could optionally include the layout name in the mapping string?

I'm looking after the user experience of this - this way we could change display config dynamically, but not apps that map to displays… this really fits into the display file, we should try and find a way for it to go there.

> > We also need more ways to match apps, as this won't allow you to run multiple WPEs mapped to different screens.
> 
> There is existing code in Frame to use apparmor to identify other snaps, we could add that as an additional matching option?

Yes, that was one of the options I was thinking of. Having a way for Frame to dynamically set the parsing up as suggested above would also separate this snap-specific handling from Mir itself.

2023-03-01 12:20 UTC, AlanGriffiths commented
OK, another approach with display:

```yaml
  side_by_side:
    cards:
    # a list of cards (currently matched by card-id)

    - card-id: 0
      OUT-1:
        # This output supports the following modes: 800x600@60.0
        #
        # Uncomment the following to enforce the selected configuration.
        # Or amend as desired.
        #
        state: enabled  # {enabled, disabled}, defaults to enabled
        mode: 800x600@60.0      # Defaults to preferred mode
        position: [0, 0]        # Defaults to [0, 0]
        orientation: normal     # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 0        # Outputs with the same non-zero value are treated as a single display
        surface-title: Cog

      OUT-2:
        surface-title: Kodi
        # This output supports the following modes: 800x600@60.0
        #
        # Uncomment the following to enforce the selected configuration.
        # Or amend as desired.
        #
        state: enabled  # {enabled, disabled}, defaults to enabled
        mode: 800x600@60.0      # Defaults to preferred mode
        position: [800, 0]      # Defaults to [0, 0]
        orientation: normal     # {normal, left, right, inverted}, defaults to normal
        scale: 1
        group: 0        # Outputs with the same non-zero value are treated as a single display
```

2023-03-01 17:26 UTC, Saviq commented
> OK, another approach with display:

Looking better, and working! I'll sleep on the `surface-title` key, maybe simpler `app-title`, or `window-title`, though I know it's not strictly correct? Don't want to need to teach people what surfaces are :)

We may want to log the surface titles encountered so those are visible on device?

2023-03-06 12:06 UTC, AlanGriffiths commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
It seems cleaner to have specific keys and not mess with parsing the value. But maybe `snap-name` would be sufficient?

2023-03-06 12:07 UTC, AlanGriffiths commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
Also, Frame could enforce "only one".

2023-03-06 13:22 UTC, Saviq commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
> It seems cleaner to have specific keys and not mess with parsing the value. But maybe `snap-name` would be sufficient?

You mean, never looking for title, only snap name? I suppose snaps creating multiple surfaces would be at a disadvantage, but that's unlikely to be common. And you already likely know the snap name, the title - not necessarily… So that may be a good compromise.

> Also, Frame could enforce "only one".

I suppose it could warn, but that's well hidden and while you get unexpected results you'll get annoyed.

2023-03-06 14:12 UTC, AlanGriffiths commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
> I suppose it could warn, but that's well hidden and while you get unexpected results you'll get annoyed.

It doesn't have to be hidden

2023-03-06 14:46 UTC, AlanGriffiths commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
> You mean, never looking for title, only snap name? I suppose snaps creating multiple surfaces would be at a disadvantage, but that's unlikely to be common. And you already likely know the snap name, the title - not necessarily… So that may be a good compromise.

Yes.

Apps that actively use the surface title for placement could probably explicitly request the output.

The downside is when there's no identifier to use if the client isn't a snap. That probably isn't a major usecase. (I can imagine using frame-it to set up bespoke desktop sessions with non-snaps and multiple outputs, but I don't think we should care.) 

Or we document the `snap-name` approach and add that `surface-title` is a harder to use fallback (with a bunch of caveats)

2023-03-06 14:48 UTC, Saviq commented on src/frame_window_manager.cpp
> +    placement_mapping.set_output_for_snap(specification, snap_name);
> It doesn't have to be hidden

There's no good way to surface such problems today when you run as a daemon…

> Or we document the snap-name approach and add that surface-title is a harder to use fallback (with a bunch of caveats)

Yeah it may well still useful, just a case of documenting precedence. Not a big cost.

2023-03-07 14:25 UTC, Saviq requested changes
Given the following config, changing the layout live does not re-position gedit when changing layouts:

```yaml
layouts:
  default:
    cards:
    - card-id: 0

  side_by_side:
    cards:
    - card-id: 0
      OUT-1:
        position: [0, 0]
        snap-name: mir-kiosk-kodi

      OUT-2:
        position: [800, 0]
        surface-title: Cog

      OUT-3:
        position: [1200, 0]
        surface-title: gedit

  two:
    cards:
    - card-id: 0
      OUT-1:
        position: [0, 0]
        surface-title: gedit

      OUT-2:
        position: [800, 0]
        snap-name: mir-kiosk-kodi

      OUT-3:
        position: [1200, 0]
        surface-title: Cog
```

Ran with:
```bash
ubuntu-frame --x11-output 800x400:400x800:400x400
```

When I stop and start gedit, that places it correctly, but not when modifying `frame.display-layout`.

2023-03-07 14:27 UTC, Saviq commented on src/frame_window_manager.cpp
> +                              specification.name().value().c_str());
This looks meh when it's not a snap, could only add the `[snap…]` bit when it is?

```
frame: [snap ""] New surface with title="gedit"
```

Or maybe like this, so it matches the config keys:

```
frame: New surface with surface-title=…
frame: New surface with snap=... surface-title=...
```

2023-03-07 16:06 UTC, AlanGriffiths commented
> When I stop and start gedit, that places it correctly, but not when modifying `frame.display-layout`.

I've not tracked down the change, but this doesn't get placed because the surface title has become "Untitled Document 1 - gedit", not "gedit"

2023-03-07 16:08 UTC, Saviq commented on src/frame_window_manager.cpp
> +            specification.output_id() = t2o.second;
Shouldn't we return here?

2023-03-07 16:08 UTC, Saviq commented on src/frame_window_manager.cpp
> +            specification.output_id() = s2o.second;
Ditto?

2023-03-07 16:40 UTC, AlanGriffiths commented on src/frame_window_manager.h
> +        std::vector<std::pair<std::string, int>> snap_name_to_output_id;
As discussed above giving useful warnings is problematic.

It could be a map, but that's unlikely to benefit us as we need to access by both title and output id.

2023-03-08 12:17 UTC, Saviq approved these changes
All good!

bors merge

2023-03-08 12:22 UTC, closed without merging