[Merged by Bors] - Authorize ubuntu-frame-osk using apparmor
MirServer/ubuntu-frame pull request #37
Opened 2021-10-26 23:30 UTC by wmww

This requires `miral::socket_fd_of()` from miral 3.4, so it switches to the dev Mir PPA and is marked as draft for now.

2021-10-29 19:27 UTC, wmww commented
Ah, I didn't realize edge uses the dev Mir ppa

2021-11-01 09:57 UTC, AlanGriffiths requested changes
The backwards compatibility needs fixing before we land.

It would be nice to fix https://github.com/MirServer/mir/issues/2194 too.

2021-11-01 09:57 UTC, AlanGriffiths commented on src/frame_main.cpp
> +#include <iostream>
I don't see these being used.

```suggestion
```

2021-11-01 09:57 UTC, AlanGriffiths commented on src/frame_main.cpp
> +    for (auto const& protocol : osk_protocols)
```suggestion
        WaylandExtensions::zwp_input_method_v2};

    for (auto const& protocol : osk_protocols)
```

2021-11-01 09:57 UTC, AlanGriffiths commented on src/snap_name_of.cpp
> +#endif
When used with Miral < 3.4 this PR should not be changing the existing behaviour. This approach breaks the existing mechanism for enabling `zwlr_layer_shell_v1` etc:  the current demo on https://snapcraft.io/ubuntu-frame-osk doesn't work.

2021-11-01 10:11 UTC, AlanGriffiths commented on src/snap_name_of.cpp
> +            << std::endl;
```suggestion
        mir::log_debug("aa_getpeercon() failed for process %d : %s", miral::pid_of(app), strerror(errno));
```

(This also requires `MIR_LOG_COMPONENT`, which should probably go in `CMakeLists.txt`:
```cmake
target_compile_definitions(frame PRIVATE MIR_LOG_COMPONENT="frame")
```

2021-11-01 19:42 UTC, wmww commented on src/snap_name_of.cpp
> +            << std::endl;
Done

2021-11-01 19:42 UTC, wmww commented on src/snap_name_of.cpp
> +#endif
Fixed

2021-11-01 19:43 UTC, wmww commented on src/frame_main.cpp
> +#include <iostream>
Fixed

2021-11-02 10:21 UTC, AlanGriffiths commented on src/frame_authorization.cpp
> +FrameAuthorization::FrameAuthorization(miral::WaylandExtensions& extensions)
Why is this a constructor? The associated class has no state to initialize: everything it does is a side-effect.

2021-11-02 15:58 UTC, wmww commented on src/frame_authorization.cpp
> +FrameAuthorization::FrameAuthorization(miral::WaylandExtensions& extensions)
Oh, right, I was going to make it cache the snap names of applications so it didn't have to look them up over and over again. I'll add that momentarily.

2021-11-02 16:23 UTC, AlanGriffiths commented on src/frame_authorization.cpp
> +FrameAuthorization::FrameAuthorization(miral::WaylandExtensions& extensions)
In that case there's a risk of a dangling `this` if the client code changes:

```c++
       FrameAuthorization{wayland_extensions}; // Who needs a name?
```

2021-11-04 10:44 UTC, AlanGriffiths commented on src/frame_authorization.cpp
> +FrameAuthorization::FrameAuthorization(miral::WaylandExtensions& extensions)
> Oh, right, I was going to make it cache the snap names of applications so it didn't have to look them up over and over again. I'll add that momentarily.

I think the right place to store this data would be `ApplicationInfo::userdata()`, that avoids the need to think about cache invalidation. (C.f. [two hard things](https://www.google.com/search?channel=fs&client=ubuntu&q=two+hard+things))

2021-11-11 10:20 UTC, AlanGriffiths commented
@wmww I think you now have everything landed in Mir to rework this with the new 3.4 APIs?

2021-11-11 17:20 UTC, wmww commented on src/frame_authorization.cpp
> +FrameAuthorization::FrameAuthorization(miral::WaylandExtensions& extensions)
Since extensions aren't given an `ApplicationInfo` and plumbing the `WindowManagerTools` needed to get it into the authorizer seems impractical, I left off caching for now.

2021-11-11 17:42 UTC, AlanGriffiths approved these changes
WFM

bos r+

2021-11-12 16:18 UTC, closed without merging