Add screenshot command
MirServer/ubuntu-frame pull request #61
Opened 2022-04-21 21:07 UTC by wmww

Draft because it requires unreleased Mir from the dev PPA.

Used grim (wayshot isn't in the Ubuntu repos, and doesn't seem better in any way relevant to us). Connects to the home plug and saves by default in the current directory.

2022-04-22 08:02 UTC, AlanGriffiths commented on scripts/bin/screenshot
> +  fi
Doesn't grim already do this by default?

2022-04-22 09:11 UTC, AlanGriffiths commented
> Connects to the home plug and saves by default in the current directory

1. Is the home plug useful? On core we'll be running as root.

2. We don't control "the current directory", even with `home` connected it may not be accessible.

Maybe we should place it under somewhere like `$SNAP_DATA_COMMON`?

2022-04-22 10:43 UTC, Saviq commented
> > Connects to the home plug and saves by default in the current directory
> 
> 1. Is the home plug useful? On core we'll be running as root.

This sounds like we need to suggest the usage of `sudo` in those circumstances? Since you're likely to _run_ it as a user?

> 2. We don't control "the current directory", even with `home` connected it may not be accessible.
> 
> Maybe we should place it under somewhere like `$SNAP_DATA_COMMON`?

I suppose we could default to that location (and return the saved location) to avoid unpleasantness when it fails to save.

2022-04-22 10:54 UTC, Saviq commented
Some experiences to maybe improve:

```shell
# trying as a user when Frame is running as root
user $> ubuntu-frame.screenshot 
ls: cannot access '/tmp/frame-display-wayland-0': Permission denied
failed to create display

# trying without displays
user $> sudo ubuntu-frame.screenshot
no wl_output

# having connected a display
user $> snap restart ubuntu-frame
Restarted.

# trying to save to user's $HOME, despite `ubuntu-frame:home` being connected
user $> sudo ubuntu-frame.screenshot
error while writing to output stream

# trying to save a directory (maybe we could support a target dir, not just a file?)
user $> sudo ubuntu-frame.screenshot snap/ubuntu-frame/common  
error while writing to output stream

# finally
user $> sudo ubuntu-frame.screenshot /var/snap/ubuntu-frame/common/file.png
user $> file /var/snap/ubuntu-frame/common/file.png 
/var/snap/ubuntu-frame/common/file.png: PNG image data, 1920 x 1080, 8-bit/color RGB, non-interlaced
```

2022-04-22 14:28 UTC, wmww commented on src/frame_main.cpp
> +
I'm of the opinion `ubuntu-frame.screenshot` should always take a screenshot of Ubuntu Frame, but we can drop this if you don't think the complexity is worth it.

2022-04-22 14:29 UTC, wmww commented on src/frame_authorization.cpp
> +};
I think getting the hard coded refactor in first is a good idea, but yeah long term I could see that making sense.

2022-04-22 14:34 UTC, wmww commented on scripts/bin/screenshot
> +  fi
It has a version. It's version includes seconds, and overwrites if multiple are taken in the same second, which in practice is about as good. I thought having the name start with `frame_` instead of end with `_grim` would be nice. Another advantage is that rolling our own naming allows us to easily switch screenshot tools.

2022-04-22 16:26 UTC, AlanGriffiths commented on src/frame_main.cpp
> +
We already have to explain the need to set `WAYLAND_DISPLAY` in our tutorials and how-tos, it is simple to apply the same advice to `ubuntu-frame.screenshot`.

In addition, this complexity isn't bullet-proof either: What happens when there are two instances of `ubuntu-frame` running? Or when run as the "wrong" user?

2022-04-22 16:28 UTC, AlanGriffiths commented on src/frame_authorization.cpp
> +};
Sure. Maybe it can be `consteval` for now?

2022-04-25 15:47 UTC, wmww commented
Constexpr was giving me issues, but I did refactor it such that we can move to making authorization an option easier.

I think I also fixed most of the footguns @Saviq ran into, including saving with an automatic name into a specific directory.

2022-04-26 13:44 UTC, Saviq commented
Must say the error messages from grim leave lots to be desired… But short of rolling our own screenshotting tool…

```shell
$ ubuntu-frame.screenshot 
Saving screenshot to /home/michal/snap/ubuntu-frame/common/frame_20220426_1325.png
failed to create display

$ sudo ubuntu-frame.screenshot
Saving screenshot to /root/snap/ubuntu-frame/common/frame_20220426_1325.png
no wl_output

$ sudo ubuntu-frame.screenshot .
Saving screenshot to ./frame_20220426_1341.png
error while writing to output stream
```

I think we should still say "Saving screenshot to…" when given a path:
```shell
$ sudo ubuntu-frame.screenshot /var/snap/ubuntu-frame/common/foo.png
$ sudo ubuntu-frame.screenshot /var/snap/ubuntu-frame/common/foo.png
```

This all looks good:
```shell
$ sudo ubuntu-frame.screenshot
Saving screenshot to /root/snap/ubuntu-frame/common/frame_20220426_1340.png

$ sudo ubuntu-frame.screenshot
Saving screenshot to /root/snap/ubuntu-frame/common/frame_20220426_1340_1.png

$ sudo ubuntu-frame.screenshot /var/snap/ubuntu-frame/common 
Saving screenshot to /var/snap/ubuntu-frame/common/frame_20220426_1341.png
```

2022-04-26 14:22 UTC, AlanGriffiths commented
> ```shell
> $ ubuntu-frame.screenshot 
> Saving screenshot to /home/michal/snap/ubuntu-frame/common/frame_20220426_1325.png
> failed to create display
> ```

Maybe we should wait for grim to succeed and report "Screenshot saved to /home/michal/snap/ubuntu-frame/common/frame_20220426_1325.png"?

2022-05-03 10:26 UTC, Saviq commented
One last thing that irks me:
```plain
$ ubuntu-frame.screenshot .
touch: cannot touch './frame_20220503_1216.png': Permission denied
```

I know a hack, but I wonder if we should replace `touch` with `$0` here?

And we should work on improving the error messages upstream. If it's trivial to build `grim`, maybe we start with patching it for our use?

2022-05-03 16:17 UTC, wmww commented
Maintaining patches is a pain. Detecting the likely error conditions and showing messages from bash is going to be easier.

2022-05-03 17:49 UTC, wmww commented
New message:
```
ubuntu-frame.screenshot: can't save to /root/frame_20220503_1049.png: Permission denied
```

2022-05-03 20:17 UTC, Saviq commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
And maintaining this isn't a pain? ;)

2022-05-04 16:40 UTC, wmww commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
Not as much as patches, in my opinion

2022-05-10 09:22 UTC, Saviq requested changes
Some tweaks inline.

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/run-client
> +export XDG_RUNTIME_DIR=$(dirname "$XDG_RUNTIME_DIR")
Seems excessive to have a separate script just for that? Did you mean it to use it elsewhere, or just future proofing?

Also, a comment why it's necessary to do this (it's not clear to me) could help.

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/screenshot
> +SCRIPT_NAME='ubuntu-frame.screenshot'
```suggestion
SCRIPT_NAME='${SNAP_INSTANCE_NAME}.screenshot'
```

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/screenshot
> +      echo "USAGE: ubuntu-frame.screenshot [output-file]"
```suggestion
      echo "USAGE: ubuntu-frame.screenshot [output-file-or-directory]"
```

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/screenshot
> +        echo "$SCRIPT_NAME: please provide a single output file" >&2
```suggestion
        echo "$SCRIPT_NAME: please provide a single output file or directory" >&2
```

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/screenshot
> +# OUTPUT_DIR is only used if OUTPUT_FILE is empty
```suggestion
```

2022-05-10 09:22 UTC, Saviq commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
I would still like us to be good citizens and suggest improvements upstream :)

2022-05-10 09:22 UTC, Saviq commented on snap/snapcraft.yaml
> +      - wayland
Hmm? Shouldn't this be up in `plugs`?

2022-05-10 09:22 UTC, Saviq commented on snap/snapcraft.yaml
> +      - home
```suggestion
      - home
      - removable-media
```

2022-05-10 19:00 UTC, wmww commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
If this was a bug then yes, but I don't see "error while writing to output stream" as all that bad an error message. I get that we want to control what our product spits out so we can make sure our customers understand it, but I don't think it's bothering anyone else too much.

2022-05-10 19:01 UTC, wmww commented on scripts/bin/run-client
> +export XDG_RUNTIME_DIR=$(dirname "$XDG_RUNTIME_DIR")
It's so it can be included in the command chain and run as part of `snap run --shell`, comment added.

2022-05-10 19:04 UTC, wmww commented on snap/snapcraft.yaml
> +      - wayland
Doesn't work, can't have plug and slot of the same name. This is wrong, but it works.

2022-05-11 10:30 UTC, Saviq commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
Yeah that's the least problematic one. Except for the "stream" part, which does not ring "file" immediately.

But:
- `failed to create display`: wut? Why are you trying to create a display!?
- `no wl_output`: Gah! What's `wl_output`!?

Maybe it's just me, but I don't think `grim` users should be expected to grok those messages.

2022-05-11 10:30 UTC, Saviq commented on snap/snapcraft.yaml
> +      - wayland
Right, but you can be explicit about it:
```yaml
  - wayland-client
    interface: wayland
```

2022-05-11 10:44 UTC, Saviq commented on scripts/bin/screenshot
> +    echo "$SCRIPT_NAME: can't save to $OUTPUT_FILE: $ERROR_MESSAGE" >&2
Yeah that's the least problematic one. Except for the "stream" part, which does not ring "file" immediately.

But:
- `failed to create display`: wut? Why are you trying to create a display!?
- `no wl_output`: Gah! What's `wl_output`!?

Maybe it's just me, but I don't think `grim` users should be expected to grok those messages.

2022-05-11 17:58 UTC, wmww commented on snap/snapcraft.yaml
> +      - wayland
Unfortunately this does not seem to work. I added this under general plugs and `wayland-client` under screenshot app plugs. The snap builds, but it fails to connect to the display.

2022-05-11 17:59 UTC, wmww commented on snap/snapcraft.yaml
> +      - home
It's not showing up here but I added this

2022-05-26 08:53 UTC, Saviq approved these changes
I'm +1 on this one, with the caveat that I'd like to improve the error messages going forward. Preferably through improving them in grim itself.

bors delegate

2022-05-26 09:17 UTC, AlanGriffiths requested changes
One tweak to naming, one discussion of what we should be trying to support.

2022-05-26 09:17 UTC, AlanGriffiths commented on scripts/bin/screenshot
> +      echo "USAGE: $SCRIPT_NAME [output-file-or-directory]"
Given the limitations on saving from a confined snap, and other failure modes, do we really want to enable specifying an output directory? Can't we just save somewhere we know we have permission and report the filename?

2022-05-26 09:17 UTC, AlanGriffiths commented on scripts/bin/screenshot
> +  CANDIDATE="$OUTPUT_DIR/frame_$(date '+%Y%m%d_%H%M')${SUFFIX:+_$SUFFIX}.png"
Maybe stick to ISO formatting? 
```suggestion
  CANDIDATE="$OUTPUT_DIR/frame_$(date '+%Y%m%dT%H:%M:%S')${SUFFIX:+_$SUFFIX}.png"
```

2022-05-26 09:17 UTC, AlanGriffiths commented on scripts/bin/screenshot
> +  echo "Saved to $OUTPUT_FILE"
Should we have (at least an option) to report the unadorned filename. I'm thinking of usage such as a script that does:

```
scp `sudo ubuntu-frame.snapshot` $dest
```

2022-05-26 09:18 UTC, Saviq commented on snap/snapcraft.yaml
> +      - wayland
This worked for me:

```diff
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -71,15 +71,14 @@ apps:
       - home
       - removable-media
       - opengl
-    slots:
-      # Should be a plug but one snap can't have both the wayland slot and plug. This works.
-      - wayland
 
 plugs:
   graphics-core20:
     interface: content
     target: $SNAP/graphics
     default-provider: mesa-core20
+  wayland-client:
+    interface: wayland
 
 parts:
   recipe-version:
```

There's an extra caveat, you need to manually connect it, which is a reason to just stick to the wayland slot. But then, maybe:

```diff
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -41,13 +41,10 @@ apps:
     command-chain: [bin/run-user, bin/run-frame]
     command: usr/local/bin/frame
     plugs:
-      - opengl                # for compositing
       - login-session-control # to run as a user login (e.g. from a VT)
       - x11                   # to run on a host X11 server
       - network-bind          # to run via X-forwarding (e.g. development in a container/VM)
       - hardware-observe      # libinput likes to scan udev
-    slots:
-      - wayland
 
   daemon:
     command-chain: [bin/run-daemon, bin/run-frame]
@@ -60,9 +57,6 @@ apps:
       HOME: $SNAP_DATA
     plugs:
       - hardware-observe      # libinput likes to scan udev
-      - opengl
-    slots:
-      - wayland
 
   screenshot:
     command-chain: [bin/anon-shm-preload, bin/run-client]
@@ -70,16 +64,16 @@ apps:
     plugs:
       - home
       - removable-media
-      - opengl
-    slots:
-      # Should be a plug but one snap can't have both the wayland slot and plug. This works.
-      - wayland
 
 plugs:
   graphics-core20:
     interface: content
     target: $SNAP/graphics
     default-provider: mesa-core20
+  opengl:
+
+slots:
+  wayland:
 
 parts:
   recipe-version:
```

2022-05-26 11:45 UTC, Saviq commented on snap/snapcraft.yaml
> +      - removable-media
That was a request from me, and I suppose if we drop the destination handling, then those should go away, too.

2022-05-26 11:45 UTC, Saviq commented on scripts/bin/screenshot
> +      echo "USAGE: $SCRIPT_NAME [output-file-or-directory]"
Having gone back'n'forth on this I feel like saving to a custom destination is fragile enough and requires massaging through enough, that I agree it's probably is not worth dealing with the fallout.

If `grim` ever becomes usable on its own for this, without all this cruft around it, we can revisit.

2022-05-26 11:45 UTC, Saviq commented on scripts/bin/screenshot
> +  echo "Saved to $OUTPUT_FILE"
With the other changes discussed, we can probably make this the only behaviour.

2022-05-26 11:45 UTC, Saviq commented on src/frame_authorization.cpp
> +};
This still needs addressing I believe?

2022-05-27 08:54 UTC, AlanGriffiths approved these changes
WFM

2022-05-27 08:54 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +      - wayland
That's what you get for preferring `ubuntu-frame.screenshot` over `ubuntu-frame-screenshot`.

(Sorry, will shut up now)

2022-05-27 09:26 UTC, Saviq commented on snap/snapcraft.yaml
> +      - wayland
Can be handled separately.

bors merge

2022-05-27 09:31 UTC, closed without merging