Identify client without AppArmor
MirServer/ubuntu-frame pull request #78
Opened 2022-07-25 16:39 UTC by AlanGriffiths

Fixes: #77

2022-07-25 19:30 UTC, wmww requested changes
I'm generally on-board with the approach, so long as the app armor failure can't be spoofed by a malicious client on a system that does have apparmor support.

I question why we're using the C filesystem functions and strings at all

2022-07-25 19:30 UTC, wmww commented on src/frame_authorization.cpp
> +                    std::string const path{buffer};
`read()` doesn't add a null terminator. `buffer` contains `"/proc/<pid>/cmdline\0"` and is otherwise undefined. Don't we need to use the size returned from `read()` to construct the string?

2022-07-26 08:00 UTC, RAOF requested changes
As this is a weakening of the security properties (my understanding is that pid racing can be made pretty reliable) I think this might want to be configurable, so that administrators can ensure that their systems don't accidentally fall into a less-secure state.

I think we should definitely address the maybe-`read`-doesn't-end-up-null-terminated issue; I'd be happy with a brute-force `memset` for that, though the fancier solution would also be fine :wink:

2022-07-26 08:00 UTC, RAOF commented on src/frame_authorization.cpp
> +                    std::string const path{buffer};
It is also not an error for `read` to return fewer than the requested number of bytes if interrupted by a signal; this would result in `buffer` not being null-terminated, and an improper memory access in the `string` constructor.

I *think* the *absolutely correct* way to do this would be to:

1. Grab a `pidfd` of the process; I *believe*¹ this ensures the kernel will not recycle the pid, even if the process terminates. (We need this so that we know the `proc` files aren't going to be replaced mid-check)
2. `stat` the `cmdline` file, to determine how many bytes we *expect*
3. `read` from `scoped_fd` until we've read as many bytes as we expect.

I think we can get away with just keeping track of how many bytes `read` has read and null-terminating (or just `memset(buffer, 0, sizeof buffer)`?), since:
1. I don't think it's actually possible to interrupt such a small `read` with a signal part way through, and
2. The failure mode is either a spurious denial or, if the attacker is very lucky, a spurious authorisation (if the attacker has installed `authenticated-snap-but-this-one-is-evil` and manages to interrupt the read at `authenticated-snap`)

For added bonus points we could handle `EINTR` here; interruption by a signal *before* any data is read is much easier to hit. 

¹: But the documentation is not great; this is implied by the docs, not outright stated.

2022-07-26 08:33 UTC, AlanGriffiths commented
> I think we should definitely address the maybe-`read`-doesn't-end-up-null-terminated issue; I'd be happy with a brute-force `memset` for that, though the fancier solution would also be fine wink

We do already zero initialize the array. (OK, we have overwritten the start, but we are guaranteed a `\0` termination.)

2022-07-26 08:34 UTC, AlanGriffiths commented on src/frame_authorization.cpp
> +                    std::string const path{buffer};
> `read()` doesn't add a null terminator. `buffer` contains `"/proc/<pid>/cmdline\0"` and is otherwise undefined.

The rest of the array is zero initialised.

2022-07-26 08:57 UTC, RAOF commented on src/frame_authorization.cpp
> +                    std::string const path{buffer};
Hah! I did indeed miss that.

2022-07-26 09:13 UTC, AlanGriffiths commented
> Grab a pidfd of the process; I believe¹ this ensures the kernel will not recycle the pid, even if the process terminates. (We need this so that we know the proc files aren't going to be replaced mid-check)

Maybe I'm being thick, but this would all have to happen while maintaining the Wayland socket pair and associated state. Is that event theoretically possible?

2022-07-26 11:34 UTC, AlanGriffiths commented
> I question why we're using the C filesystem functions and strings at all

I think your point is proven in that most of the discussion wouldn't happen using c++ file IO

2022-07-26 20:18 UTC, wmww approved these changes
LGTM

2022-07-27 06:56 UTC, RAOF commented
> > Grab a pidfd of the process; I believe¹ this ensures the kernel will not recycle the pid, even if the process terminates. (We need this so that we know the proc files aren't going to be replaced mid-check)
> 
> Maybe I'm being thick, but this would all have to happen while maintaining the Wayland socket pair and associated state. Is that event theoretically possible?

I think so? Have the malicious client spawn a child process, which initiates the connection, hands the fd to the parent, and then dies. The parent might need to do some libwayland surgery to transfer a bit of state, but this leaves the parent with an open Wayland connection that Mir identifies as coming from a pid that no longer exists.

2022-07-27 06:57 UTC, RAOF reviewed
Yeah, that looks better.

I'd still like this gated behind a config option, or at least have a config option to *dis*able this behaviour.

2022-07-28 07:43 UTC, RAOF approved these changes
Yeah, I think I'm OK with this now.

bors r+

2022-07-28 08:19 UTC, AlanGriffiths commented
bors retry

2022-07-28 08:23 UTC, AlanGriffiths commented
"Component "api.snapcraft.io - refresh" and a few other components are Down" - https://status.snapcraft.io/

Will retry later

2022-07-28 08:55 UTC, AlanGriffiths commented
bors retry

2022-07-28 09:00 UTC, closed without merging