Add crash reporter
MirServer/ubuntu-frame pull request #80
Opened 2022-08-02 00:00 UTC by graysonguarino

Combines the wallpaper into a CrashReporter which, when a log file is created at a certain location, displays the log file on screen.

Creating as draft because I haven't yet looked into where Snapcraft puts logs by default.

2022-08-02 07:34 UTC, Saviq requested changes
> Creating as draft because I haven't yet looked into where Snapcraft puts logs by default.

Snap**craft** doesn't run in this context, FWIW, but regardless - there's nowhere "default" logs are put that you should be considering.

The default path under snap confinement needs to be under `$SNAP_USER_DATA`, as you won't be able to read outside of this location.

In addition, we could think of a [content slot](https://snapcraft.io/docs/content-interface) so that connected confined snaps can write there.

In general, I wouldn't call/think of them as "logs", but rather "diagnostics" - we don't want to be following a log file (not only because that will quickly be unreadable as it fills up the screen, unless we `tail` it by some amount). Operators should craft the diagnostics file according to their needs, so it's mostly static on screen.

2022-08-02 07:34 UTC, Saviq commented on snap/snapcraft.yaml
> +  LOG_DIR: $SNAP/log
I wouldn't call these "logs", as that may suggest we'll be following the log as it gets written to? Maybe something along "diagnostics"?

2022-08-02 07:34 UTC, Saviq commented on src/CMakeLists.txt
>  )
This should be unnecessary, in modern CMake linking sets up include dirs as well.

2022-08-02 07:34 UTC, Saviq commented on src/startup_client.cpp
> +    }
This looks like could be a DoS problem. We should think of only updating it every `$seconds`.

2022-08-02 07:34 UTC, Saviq commented on src/startup_client.cpp
> +    remove(file_path.c_str());
We shouldn't do that, we should use / monitor changes on existing files, too.

Think of a boot script generating the diagnostic file before Frame gets to here.

2022-08-02 07:34 UTC, Saviq commented on src/startup_client.cpp
> +        IN_CREATE | IN_MODIFY
Wonder if we should [do `IN_CLOSE_WRITE`](https://stackoverflow.com/questions/32377517/inotify-event-in-modify-occurring-twice-for-tftp-put) instead?

2022-08-02 07:35 UTC, Saviq commented on snap/snapcraft.yaml
> +  LOG_DIR: $SNAP/log
This looks like leftover?

2022-08-02 13:27 UTC, AlanGriffiths commented on src/startup_client.h
> +    }
Would probably be wrong if used on big-endian architectures. But as it isn't used, I can't be sure.

Anyway, not needed

2022-08-02 13:37 UTC, AlanGriffiths commented on src/startup_client.h
> +    uint8_t a;
I don't think alpha is ever usefully anything but 255
```suggestion
    uint8_t const a = 0xff;
```

2022-08-02 13:38 UTC, AlanGriffiths commented on src/startup_client.h
> +    }
Use a delegating constructor, not assignment; and, I think, alpha should be 255

2022-08-02 15:15 UTC, graysonguarino commented on src/startup_client.cpp
> +        IN_CREATE | IN_MODIFY
Agreed.

2022-08-02 16:16 UTC, graysonguarino commented on src/startup_client.h
> +    uint8_t a;
This `Pixel` is designed to maintain compatibility with the old definition of `Pixel` (`typedef uint8_t Pixel`) which meant a "real" pixel (not a subpixel) had to be accessed as a `Pixel*`.

Assigning the alpha value to a const would break the ability to cast a `uint8_t*` pixel to a `Pixel`. Instead, I think we should set the alpha value to `0xFF` via a default in the `Pixel()` constructor.

2022-08-04 16:42 UTC, AlanGriffiths commented on src/startup_client.h
> +    uint8_t a;
> ability to cast a uint8_t* pixel to a Pixel

That is undefined behaviour. Best avoided

2022-08-05 02:42 UTC, wmww commented on src/startup_client.h
> +    uint8_t a;
C++ can't change the order of data members, so if you static assert that `sizeof(Pixel) == 4` than essentially it is defined that a `Pixel*` can be coasted to a `uint8_t*`, right? How could it represent a `Pixel` as anything other than the 4 `uint8_t`s in a row?

2022-08-05 04:42 UTC, RAOF commented on src/startup_client.h
> +    uint8_t a;
It's a type-based aliasing violation; you are only allowed to dereference memory through a type-compatible pointer or an `unsigned char` pointer.

Now, `uint8_t` is *almost certainly* a typedef to `unsigned char` on every platform we care about, but a compiler assuming any Pointer* accesses don't alias an `uint8_t*` accesses would be technically correct.

2022-08-05 05:11 UTC, wmww commented on src/startup_client.h
> +    uint8_t a;
[this](https://stackoverflow.com/a/2088428) and [this](https://stackoverflow.com/a/60536461) seem to indicate it's fine in at least some cases. It seems that you have to pay for ?? the actual standard, and the versions I found online aren't very searchable so I can't find what exactly it says, but I know the C standard explicitly allows using a pointer to a struct as a pointer to the first member. Is C++ different?

2022-08-05 05:17 UTC, wmww commented on src/startup_client.h
> +    uint8_t a;
[here](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) is where it is in the C standard, 6.7.2.1 paragraph 13:
> Within a structure object, the non-bit-field members and the units in which bit-fields
reside have addresses that increase in the order in which they are declared. A pointer to a
structure object, suitably con verted, points to its initial member (or if that member is a
bit-field, then to the unit in which it resides), and vice v ersa. There may be unnamed
padding within a structure object, but not at its beginning.

2022-08-05 06:15 UTC, RAOF commented on src/startup_client.h
> +    uint8_t a;
Hm. I'm certainly no spec authority, but my reading of that is a guarantee that given
```
struct Foo
{
    int a;
    int b;
};

Foo bar;
```
It's guaranteed that `&bar.a == static_cast<int*>(&bar)`. It doesn't appear to say anything about *access* through that pointer. :woman_shrugging: 

There are then two questions:
1. Is it satisfying the type-based aliasing rules (I'm honestly not sure), and
2. If you want to use the `uint8_t*` as an array, is it guaranteed that `&bar.b == &bar.a + 1` (it is not, compilers are free to add whatever padding they wish).

2022-08-05 09:48 UTC, AlanGriffiths commented on src/startup_client.h
> +    uint8_t a;
People, the first member of a structure object can be accessed casting the object address/reference to the member type address/reference. This support is motivated by the "tagged variant" idiom.

But that doesn't imply the opposite conversion, from member address to object address is permitted. That is only guaranteed by the standard _if the original address was taken from an actual object_, and only cast via `void*` or `char*` and back. (One reason for this is that the object type may have stricter alignment constraints than the member type - while this doesn't apply here, nobody was motivated to draft standard text to support such special cases.)

2022-08-05 18:16 UTC, wmww commented on src/startup_client.h
> +    uint8_t a;
So what you're saying is
```c++
uint8_t* buffer = new uint8_t[400];
Pixel* pixels = static_cast<Pixel*>(buffer);
```
is undefined but
```c++
Pixel* pixels = new Pixel[100];
uint8_t* buffer = static_cast<uint8_t*>(pixels);
```
is fine?

2022-08-05 18:17 UTC, wmww commented on src/startup_client.h
> +    uint8_t a;
> If you want to use the uint8_t* as an array, is it guaranteed that &bar.b == &bar.a + 1 (it is not, compilers are free to add whatever padding they wish).

This is why you static assert that sizeof(Pixel) == 4.

2022-08-08 16:33 UTC, graysonguarino commented on src/startup_client.h
> +    uint8_t a;
We only need to assert sizeof(Pixel) == 4 once in the codebase to ensure this since what we're checking is compiler behavior, right? So a `static_assert(sizeof(Pixel) == 4)` after the declaration of `Pixel` would guarantee this?

(I'm currently reading about aliasing [here](https://developers.redhat.com/blog/2020/06/02/the-joys-and-perils-of-c-and-c-aliasing-part-1#objects_and_types_in_c_and_c__).)

2022-08-08 16:57 UTC, AlanGriffiths commented on src/startup_client.h
> +    uint8_t a;
> So what you're saying is

No.

The language standard is saying that:

```c++
Pixel foo;

auto bar = reinterpret_cast<uint8_t&>(foo);
```

Is OK (because we're meeting a bunch of criteria, including it being the type of the first member). And that variants that are not equivalent, like accessing the second member, are not defined behaviour.

2022-08-15 16:29 UTC, AlanGriffiths requested changes
Sorry, a lot needs dealing with

2022-08-15 16:29 UTC, AlanGriffiths commented on src/startup_client.h
> +struct Pixel
Given the discussion this has generated and the problems involved in its use I suspect `Pixel` is a poor abstraction and we would be better without it.

The best way to treat raw memory is as an array of `unsigned char` (with, for the paranoid, an assert that `sizeof(unsigned char) == sizeof(unit8_t)`). IIRC using `unit8_t` is problematic as it doesn't have special treatment in the language, nor is it guaranteed (when it exists) to have the same representation as `unsigned char`. (I agree that it would be mad to use different representations, but I don't think the language standards says anything on the subject.)

2022-08-15 16:29 UTC, AlanGriffiths commented on src/startup_client.cpp
> +    }
Shouldn't there be a way to exit this loop on shutdown? Otherwise the process will "hang".

And shouldn't we wait on ioctl, not burn cycles by sleep/polling?

Have a look into adding an ioctl FD to the `poll()` processing in `FullscreenClient::run()` - that's an efficient way to move processing onto a single thread.

2022-08-15 16:29 UTC, AlanGriffiths commented on src/startup_client.cpp
> +    };
We should be supplying the font as part of the snap, no need to be searching for multiple fonts in multiple locations.

2022-08-15 16:29 UTC, AlanGriffiths commented on src/startup_client.cpp
> +            uint8_t const glyph_alpha = ((int)glyph_row[glyph_x.as_int()] * colour.a) / 255;
In principle, we don't like C-style casts, but that aside why are we casting to a signed type?

2022-08-15 16:29 UTC, AlanGriffiths commented on src/startup_client.cpp
> +        uint8_t* const glyph_row = glyph->buffer + (glyph_y.as_int() * glyph->pitch);
I think `unit8_t` is technically only right when it is a typedef for `unsigned char`. Better to use `unsigned char`

2022-08-15 16:51 UTC, graysonguarino commented on src/startup_client.cpp
> +    };
This will lock us in to the assumption that Frame will only be run as a snap as this can break functionality when running the binary directly. Is this okay?

2022-08-15 16:58 UTC, AlanGriffiths commented on src/startup_client.cpp
> +    };
It locks us into the assumption that the path to the font is supplied. That can be done outside the snap too.

2022-08-17 21:31 UTC, graysonguarino commented
Reverting to draft new issues are cleaned up

2022-08-17 21:43 UTC, graysonguarino commented on src/startup_client.h
> +    uint8_t a;
I introduced the abstraction to help fix a bug I couldn't figure out, but if it's gonna cause this much trouble, let's shelve it. I got the bug figured out the old way.

2022-08-17 21:43 UTC, graysonguarino commented on src/startup_client.h
> +    };
They say hindsight is 20/20, but I've got no idea why *that* was my solution.

2022-08-22 22:13 UTC, graysonguarino commented
Reopening as all necessary changes should be made. Only potential issue I can find is that it appears that the snap is able to see when the diagnostic file is created, but it cannot read its contents (due to permissions issues I assume.) Any advice on fixing this?

2022-08-25 16:21 UTC, AlanGriffiths commented on src/frame_main.cpp
> +                              "diagnostic-path",  "Path (including filename) of diagnostic file", "/home/$USER/Documents/log/diagnostic.txt"},
This default is _never_ going to work.

Firstly, there's no shell to expand `$USER`, so this will be taken literally;
Secondly, when running as root, `$HOME` is not `'home/root`; and,
Thirdly, when running as a snap, there will be no access to the user's `$HOME` directory.

I suggest:
1. not providing a default (and, if no path is provided, don't try to use it); and,
2. for now, use the `environment` stanza to provide it with:

```yaml
environment:
  # Prep for Mir
  MIR_SERVER_DIAGNOSTIC_PATH: ${SNAP_USER_HOME}/log/diagnostic.txt
```

When doing the content interface, we can redirect at that.

2022-08-26 16:27 UTC, AlanGriffiths requested changes
The `diagnostic-path` argument should be optional; and, if it is not supplied then, Frame should start without the diagnostic handling.

2022-08-26 16:27 UTC, AlanGriffiths commented on src/egfullscreenclient.cpp
> +    diagnostic_signal{get_diagnostic_fd(diagnostic_path)},
Calling a non-static member function in an initializer list is at best fragile, and very easily leads to undefined behaviour. (It must not access any state that has not already been initialized)

2022-08-26 16:27 UTC, AlanGriffiths commented on src/startup_client.cpp
> +    boost::replace_all(path_string, "$USER", getenv("USER"));
Oh, this is a nasty hack to get around the default string having `$USER`. But it will give the impression that shell variables are expanded, and that isn't true in general. (It would be better to do this generating the default value, but I don't recommend having a default value.)

2022-08-26 16:27 UTC, AlanGriffiths commented on src/startup_client.cpp
> +    }
This isn't going to work once we move to a content interface: that directory will only exist if the interface is plugged and we don't want to require that.

In any case, Frame should be _able_ to start without the directory existing either because the option isn't supplied and we don't check, or because we simply `log_info` when it doesn't.

I prefer the "no option, don't look" approach. In which case `run-frame` should check for the existence of `$(basename $MIR_SERVER_DIAGNOSTIC_PATH)` and `unset MIR_SERVER_DIAGNOSTIC_PATH` if it isn't there.

Also, any diagnostic should refer to "diagnostic", not to "log".

2022-08-26 16:27 UTC, AlanGriffiths commented on src/frame_main.cpp
> +                              "diagnostic-path",  "Path (including filename) of diagnostic file", "/home/$USER/Documents/log/diagnostic.txt"},
Actually, all that is needed for the content interface is the following:

```yaml
environment:
  ...
  MIR_SERVER_DIAGNOSTIC_PATH: $SNAP/diagnostic/diagnostic.txt
```

and 

```yaml
plugs:
  ...
  ubuntu-frame-diagnostic:
    interface: content
    target: $SNAP/diagnostic
```

2022-08-29 23:09 UTC, graysonguarino reviewed
I believe that this should now be stable enough for a proper review as a MVP for CrashReporter. This should maintain compatibility both in the snap and when run as the binary, with or without a diagnostic file.

In future PRs (or in this one if requested), it may be wise to detect if a line in the diagnostic is printing offscreen and kick it to a new line.

2022-08-29 23:09 UTC, graysonguarino commented on src/startup_client.cpp
> +    }
Agreed, this was the wrong approach.

Now, `set_diagnostic_path()`
1. Checks if $MIR_SERVER_DIAGNOSTIC_PATH exists in the environment, and if it is and no option is given, make that the path.
2. Else, check the validity of the given option (if there is one at all) and either make that the path or disable crash reporting.

2022-08-29 23:09 UTC, graysonguarino commented on src/startup_client.cpp
> +    boost::replace_all(path_string, "$USER", getenv("USER"));
This was a temporary hack until I changed this to a regex (forgot to push the `TODO` doc, oops) but now regexing should be entirely unnecessary.

2022-09-01 00:17 UTC, wmww commented
After discussing the current progress in our sync, my recommendation is to get the core crash reporter merged first and then look into adding a delay.

2022-09-01 09:57 UTC, AlanGriffiths requested changes
Lots of nits.

As none of these are deep, maybe we should try pairing to address them? Ping me when online.

2022-09-01 09:57 UTC, AlanGriffiths commented on scripts/bin/run-frame
> +fi
What is the purpose of this?

"If MIR_SERVER_DIAGNOSTIC_PATH is unset or empty, then unset it"

But we use the `environment` stanza to set it to something.

2022-09-01 09:57 UTC, AlanGriffiths commented on snap/hooks/install
> +chmod 666 $SNAP_DATA/diagnostic/diagnostic
```suggestion
mkdir -p "(dirname "$MIR_SERVER_DIAGNOSTIC_PATH")" -m 777
touch "$MIR_SERVER_DIAGNOSTIC_PATH"
chmod 666 "$MIR_SERVER_DIAGNOSTIC_PATH"
```

2022-09-01 09:57 UTC, AlanGriffiths commented on src/egfullscreenclient.cpp
> +            "Initializing inotify failed with error " + std::to_string(diagnostic_signal)));
There's little point in reporting `-1`, you should be reporting `errno` (and using `std::system_error`).

It also good practice to report `errno` errors as soon as possible after the call that sets it. (And, especially, before using `diagnostic_signal` a few lines above)

2022-09-01 09:57 UTC, AlanGriffiths commented on src/egfullscreenclient.cpp
> +    inotify_event inotify_buffer[INOTIFY_BUF_LEN];
I'd be really surprised if what this code does is what you think it does

2022-09-01 09:57 UTC, AlanGriffiths commented on src/egfullscreenclient.h
> +#include <ctime>
Is this header needed?

2022-09-01 09:57 UTC, AlanGriffiths commented on src/startup_client.h
> +#define FRAME_CRASH_REPORTER
Include guard doesn't match filename

2022-09-01 09:57 UTC, AlanGriffiths commented on src/startup_client.h
> +class StartupClient
This isn't a good name. It gives no clue what it is for, or that it continues to run after startup.

2022-09-01 17:14 UTC, graysonguarino commented on src/startup_client.h
> +class StartupClient
I have decided to go for BackgroundClient as a double-entendre. It 1) displays the wallpaper background and 2) is always running in the background.

2022-09-06 17:23 UTC, AlanGriffiths requested changes
Didn't finish this review. "Comments so far"

2022-09-06 17:23 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +  MIR_SERVER_DIAGNOSTIC_PATH: $SNAP_DATA/diagnostic/diagnostic
Just a thought: maybe call it `diagnostic.txt` to give a clue about the content?

2022-09-06 17:23 UTC, AlanGriffiths commented on src/background_client.cpp
> +    if (auto env = getenv("MIR_SERVER_DIAGNOSTIC_PATH"))
Don't use `getenv()` for this. Use a `miral::ConfigurationOption`

2022-09-07 09:09 UTC, AlanGriffiths requested changes
OK, I tried running this and saw several issues.

1. The text displayed when I first updated `/var/snap/ubuntu-frame/x1/diagnostic/diagnostic.txt` was in the top left corner. It would be better to have a margin or to centre the text (both the miral-shell and egmde examples centre the text);
2. When I subsequently updated the `/var/snap/ubuntu-frame/x1/diagnostic/diagnostic.txt` the text didn't change; and,
3. When I exited Frame there was a `Segmentation fault` (sorry, no dump: it's a snap).

2022-09-07 09:09 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +  MIR_SERVER_DIAGNOSTIC_PATH: $SNAP_DATA/diagnostic/diagnostic.txt
Maybe $SNAP_COMMON_DATA would be better?

2022-09-07 09:09 UTC, AlanGriffiths commented on snap/hooks/install
> +touch "$MIR_SERVER_DIAGNOSTIC_PATH"
Do we actually need to create a file? Should there be some default content?

2022-09-07 14:55 UTC, graysonguarino commented on snap/hooks/install
> +touch "$MIR_SERVER_DIAGNOSTIC_PATH"
I believe that the blank file should be created so that clients are guaranteed a file to write to instead of having to create it themselves.

As far as default content goes, since the crash screen won't be triggered until modification of the diagnostic file after polling has started, the default content wouldn't get displayed. I think we should leave the content of the file up to the end user.

2022-09-07 20:13 UTC, graysonguarino commented
> OK, I tried running this and saw several issues.
> 
> 1. The text displayed when I first updated `/var/snap/ubuntu-frame/x1/diagnostic/diagnostic.txt` was in the top left corner. It would be better to have a margin or to centre the text (both the miral-shell and egmde examples centre the text);
>> Should this be worried about in the initial PR? I think it would be wise to start a second PR to improve the text handling entirely. For example, this revision will gladly overflow text past the bounds of the display. I think that both of those issues should be addressed later on. Additionally, are we sure we want to center the text? If we are treating the diagnostic file as a "simplified log", shouldn't it read like terminal output? If we are treating this more like a Windows blue screen for example, then the centered text makes more sense. Or should this be a configuration option?
> 2. When I subsequently updated the `/var/snap/ubuntu-frame/x1/diagnostic/diagnostic.txt` the text didn't change; 
>> This was caused by strange behavior when watching the parent directory instead of the diagnostic file. This was initially an intentional design decision because we were expecting the clients to create `diagnostic.txt` once it was ready to display a crash screen, but that expectation has since changed and this behavior is because I hadn't fully updated the code to the new expectation. If we are always guaranteed the existence of `diagnostic.txt`, this simplifies the polling code.
> 3. When I exited Frame there was a `Segmentation fault` (sorry, no dump: it's a snap).
>> This was caused by me holding a `shared_ptr` to `BackgroundClient::Self` instead of a `weak_ptr`. Not entirely sure why I felt that needed to be a `shared_ptr` in the first place.

2022-09-07 23:51 UTC, graysonguarino commented
It seems like there was an issue introduced to the snap after d31660e. Not sure why watching the diagnostic file instead of its parent path is messing with inotify. Will look more into this in the morning.

2022-09-09 11:04 UTC, AlanGriffiths commented
I'm going to leave a bunch of questions for discussion. @Saviq you probably have thoughts on these:

1. Do we need to provide an option for the font? And do we need to package 20 fonts to support this?
2. Do we want to provide options to control the size of text, and margins? (I had expected to copy the prior art in miral-shell and egmde which auto-scales and centres the text)
3. If the `diagnostic.txt` file is there, do we want to display it (possibly after allowing an interval for clients to start)? If we restart after displaying `diagnostic.txt` then we don't continue to display the `diagnostic.txt`.

2022-09-09 11:52 UTC, Saviq commented
>     1. Do we need to provide an option for the font? And do we need to package 20 fonts to support this?

No, just use the Ubuntu font.

>     2. Do we want to provide options to control the size of text, and margins? (I had expected to copy the prior art in miral-shell and egmde which auto-scales and centres the text)

The latter would be best. We then give the operator effectively the same level of control, but not force them to use it (i.e. whatever you do, it will look sane).

>     3. If the `diagnostic.txt` file is there, do we want to display it (possibly after allowing an interval for clients to start)? If we restart after displaying `diagnostic.txt` then we don't continue to display the `diagnostic.txt`.

Yes, we should. The diagnostic file may well be static across the lifetime of the device.

2022-09-13 13:44 UTC, AlanGriffiths requested changes
When we start we need to display any existing diagnostics, not wait for the first change.

There are examples of automatically scaling and positioning the text here:

https://github.com/MirServer/mir/blob/d1d67d085c8340999d1ff472113daa93e9436468/examples/example-server-lib/decoration_provider.cpp#L176

And here:

https://github.com/AlanGriffiths/egmde/blob/0f273784f8caddd676fc03e569ff6eaf7416187f/printer.cpp#L93

2022-09-13 13:44 UTC, AlanGriffiths commented on src/background_client.cpp
> +    std::atomic<bool> diag_exists = false;
Dead code

2022-09-13 13:47 UTC, AlanGriffiths commented on src/background_client.h
> +using Colour = unsigned char;
Here's what I mean:

[diff.txt](https://github.com/MirServer/ubuntu-frame/files/9557710/diff.txt)

2022-09-13 15:55 UTC, AlanGriffiths commented on src/background_client.h
> +using Colour = unsigned char;
I'm OK with a typedef (see the diff above). Just not with the way it represents several different things none of which correspond to the name.

2022-09-14 10:49 UTC, AlanGriffiths requested changes
When we start we need to display any existing diagnostics, not wait for the first change.

There are examples of automatically scaling and positioning the text here:

https://github.com/MirServer/mir/blob/d1d67d085c8340999d1ff472113daa93e9436468/examples/example-server-lib/decoration_provider.cpp#L176

And here:

https://github.com/AlanGriffiths/egmde/blob/0f273784f8caddd676fc03e569ff6eaf7416187f/printer.cpp#L93

2022-09-14 10:49 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +    - usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
This doesn't quite work as intended:
```plain
$ find /snap/ubuntu-frame/current/usr/share/fonts/
/snap/ubuntu-frame/current/usr/share/fonts/
/snap/ubuntu-frame/current/usr/share/fonts/truetype
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
/snap/ubuntu-frame/current/usr/share/fonts/truetype/ubuntu
/snap/ubuntu-frame/current/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
```
But poking a bit further, `truetype/dejavu/*` is being pulled in by grim!

2022-09-14 10:49 UTC, AlanGriffiths commented on snap/snapcraft.yaml
> +    - usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
I don't think grim needs *any* fonts so we want:
```yaml
  grim:
    plugin: nil
    stage-packages: [grim]
    prime:
      - -usr/share/fonts/truetype/dejavu
```

2022-09-14 10:49 UTC, AlanGriffiths commented on src/background_client.cpp
> +#include <miral/configuration_option.h>
We don't use this here!

```suggestion
#include <mir/fatal.h>
```

2022-09-14 10:49 UTC, AlanGriffiths commented on src/background_client.h
> +    uint y_margin_percent;
I dislike leaving these uninitialized until set by configuration, it takes non-local reasoning to see whether we use uninitialized values.

2022-09-15 09:34 UTC, AlanGriffiths commented on src/background_client.h
> +        geom::Height height,
Why? The change from `int32_t` to `geom::Width` & `geom::Height` makes the code less clear and more verbose.

While the _WholeValue_ pattern can reduce a class of errors, it doesn't help if all that is done is extract the value and use that everywhere.

2022-09-15 19:06 UTC, graysonguarino commented on src/background_client.h
> +        geom::Height height,
I'll talk to Sophie and Chris tonight about the WholeValue pattern because I am clearly a bit foggy on my understanding of it and what problems it solves.

2022-09-16 13:13 UTC, AlanGriffiths requested changes
Some small nits, but getting close

2022-09-16 13:13 UTC, AlanGriffiths commented on src/frame_main.cpp
> +                               "diagnostic-y-margin",     "Size of x-axis margin (in percentage of display height) for diagnostic", "5"},
I see no value in having configuration options for the margin(s). We should simply hard code the value.

(In view of that it is moot that the description is misleading. These values are the total of "top+bottom"/"left+right" margins: i.e. twice size of each of the actual margins.)

2022-09-16 16:12 UTC, AlanGriffiths approved these changes
I'm OK with this. @graysonguarino might want to tidy up one or more things I mentioned so:

bors delegate

2022-09-16 16:12 UTC, AlanGriffiths commented on src/background_client.cpp
> +            memcpy(buffer + current_x, new_pixel, pixel_size);
Non blocking: you can avoid indexing as follows:
```suggestion
        for (auto current_x = buffer; current_x != buffer + pixel_size*width; current_x += pixel_size)
        {
            memcpy(current_x, new_pixel, pixel_size);
```

But the compiler probably rewrites for you anyway

2022-09-16 16:46 UTC, graysonguarino commented
bors merge

2022-09-16 16:49 UTC, AlanGriffiths approved these changes
bors merge

2022-09-16 16:54 UTC, closed without merging