Add Frame Diagnostic delay
MirServer/ubuntu-frame pull request #89
Opened 2022-10-05 21:30 UTC by graysonguarino

This is dependent on https://github.com/MirServer/mir/pull/2646 but adds the requested delay feature to Frame Diagnostic.

There are currently issues with 2646 that are documented there, so this will start as a draft.

2022-10-06 13:22 UTC, AlanGriffiths requested changes
Some quick comments

2022-10-21 16:04 UTC, Saviq requested changes
From a user perspective, the diagnostic should only be shown when something went wrong (the client app didn't show up for $delay). So you need to start the alarm on startup, and then when the last surface goes away - and cancel the alarm when a surface comes in.

We will need to think about the wallpaper and the OSK getting in the way of that, though.

Otherwise we'll be showing the diagnostic on e.g. client app getting refreshed.

That said, we may need to come up with some additional logic for when the client app cycles on and off all the time - but that would be a separate task.

2022-10-21 16:19 UTC, AlanGriffiths requested changes

2022-10-21 16:19 UTC, AlanGriffiths commented on src/egfullscreenclient.cpp
> +            diagnostic_timer_handle = runner->register_fd_handler(mir::Fd{timer_fd}, [this](int){ notify_diagnostic_delay_expired(); });
This will not compile with the current release of Mir (nor the current 2.10 branch)

We can use preprocessor checks of MIRAL_VERSION to conditionally compile code for pre-release versions of Mir.
```c++
#if MIRAL_VERSION >= MIR_VERSION_NUMBER(3, 7, 0)
    // "new Mir" code
#else
    // "old Mir" code
#endif
```

2022-10-21 16:19 UTC, AlanGriffiths commented on src/frame_main.cpp
> +    MirRunner* const runner = new MirRunner(argc, argv);
Do not create objects with raw `new` - they are not "owned" and will leak

```suggestion
    MirRunner runner{argc, argv};
```

2022-10-21 16:19 UTC, AlanGriffiths commented on src/egfullscreenclient.cpp
> +            diagnostic_timer_handle = runner->register_fd_handler(mir::Fd{timer_fd}, [this](int){ notify_diagnostic_delay_expired(); });
Presumably on "old" Mir we can just call `notify_diagnostic_delay_expired();` immediately?

2022-10-25 16:13 UTC, AlanGriffiths approved these changes
OK, not sure if @Saviq wants to review...

2022-10-25 16:41 UTC, closed without merging