Clarify diagnostic-path requirement
MirServer/ubuntu-frame pull request #96
Opened 2022-10-25 16:24 UTC by graysonguarino

Fixes #93 by clarifying an absolute path is needed for the `--diagnostic-path` option.

This is if we consider `./` to be a macro that gets an absolute path from a relative path. Not sure how to specify this without getting wordier.

2022-10-25 16:28 UTC, Saviq requested changes
As [Alan commented](https://github.com/MirServer/ubuntu-frame/issues/93#issuecomment-1287182956), it's not actually that, rather it needs to resolve a relative path without slashes?

Not sure where this (weird) behaviour comes from…

2022-10-25 16:38 UTC, AlanGriffiths requested changes
The problem is that `diagnostic-path` is split into "directory" and "file" and then existence of the directory is tested. But, if only a filename is supplied then "directory" is empty and the logic breaks.

2022-10-25 16:38 UTC, AlanGriffiths commented on src/frame_main.cpp
> +                               "diagnostic-path",  "Absolute path (including filename) of diagnostic file", ""},
This is wrong. Relative paths also work

2022-10-26 14:42 UTC, graysonguarino commented
It may be wise to drop this PR in favor of merging only #97. They both dealt with the same lines of the same code and the newer PR fixes both #93 and #94.

2022-10-26 14:47 UTC, closed without merging